### PR TITLE
Silence bogus warning: Warning: CudaSirtAlgorithm3D: unused configuration options: SinogramMaskId

### PR DESCRIPTION
**Pull request by kalvdans**
Warning: CudaSirtAlgorithm3D: unused configuration options: SinogramMaskId

### CODE REVIEW

**Comment by wjp** [comment]
Thank you; I've merged this manually.

**Comment by kalvdans** [comment]
For reference, the merge was d7746d6d0c9172a6176d7467e68f96315d34b7b2.

**Comment by kalvdans** [comment]
This change got lost in the merge 6504cffdbe74d9b671222a7ec24b26fbb4f871f0 . I'll create a new pull request to get it included again!

**Comment by wjp** [comment]
Oops, sorry about that. I wonder what happened there. Thanks for noticing.

**Pull request closed without merging**
